apiVersion: v1
kind: Service
metadata:
  name: xbrl-to-json-arelle-service
  labels:
    app: xbrl-to-json-arelle
spec:
  selector:
    app: xbrl-to-json-arelle
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
  type: ClusterIP