apiVersion: v1
kind: Service
metadata:
  name: xbrl-to-json-backend-service
  labels:
    app: xbrl-to-json-backend
spec:
  selector:
    app: xbrl-to-json-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP