apiVersion: v1
kind: Service
metadata:
  name: xbrl-to-json-frontend-service
  labels:
    app: xbrl-to-json-frontend
spec:
  selector:
    app: xbrl-to-json-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5173
  type: ClusterIP